name: dev_finance
services:
  postgres:
    image: bitnami/postgresql:latest
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: dev_finance
    volumes:
      - pgdata:/bitnami/postgresql
  redis:
    image: redis:8.0-rc1
    restart: always
    command: redis-server
    ports:
      - "6379:6379"
  traefik:
     image: traefik:v3.4
     ports:
       - "80:80"
     volumes:
       - /var/run/docker.sock:/var/run/docker.sock

volumes:
  pgdata: