name: dev_finance
services:
  postgres:
    image: bitnami/postgresql:latest
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: dev_finance
    volumes:
      - pgdata:/bitnami/postgresql

volumes:
  pgdata: